package com.dimowner.audiorecorder.v2.navigation

object Routes {

    const val HOME_SCREEN = "HOME_SCREEN"
    const val RECORDS_SCREEN = "RECORDS_SCREEN"
    const val SETTINGS_SCREEN = "SETTINGS_SCREEN"
    const val RECORD_INFO_SCREEN = "RECORD_INFO_SCREEN"
    const val DELETED_RECORDS_SCREEN = "DELETED_RECORDS_SCREEN"
    const val COMPOSE_PLAYGROUND_SCREEN = "COMPOSE_PLAYGROUND_SCREEN"
    const val DETAILS_SCREEN = "DETAILS_SCREEN"
    const val WELCOME_SCREEN = "WELCOME_SCREEN"
    const val WELCOME_SETUP_SETTINGS_SCREEN = "WELCOME_SETUP_SETTINGS_SCREEN"

    const val USER_NAME = "NAME"
    const val ANIMAL_SELECTED = "ANIMAL_SELECTED"
    const val RECORD_INFO = "RECORD_INFO"
}
